In [4]:
import numpy as np

In [ ]:
1. Array Creation

In [5]:
#Question:1 An array of integers from 1 to 10
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#Question:2 An array of five zeros.

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
# Question:3 An array of five ones

np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
# Question:4 An array of even numbers from 2 to 20

np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
2. Array Properties

In [94]:
#Queestion:1 Shape
#Create a 3 × 4 NumPy array and find:

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
#Question:2 Shape

np.shape(a)

(3, 4)

In [23]:
#Question:3 Size

np.size(a)

12

In [95]:
#Question:4 Number of dimensions

np.ndim(a)

2

In [25]:
#Question:5 data type

type(a)

numpy.ndarray

In [ ]:
3. Indexing and Slicing

In [28]:
#Given the array:
a=np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(a)

[10 20 30 40 50 60 70 80]


In [29]:
#Perform the following:
#Question1: Print the first element.

print(a[0])    

10


In [30]:
#Question:2 Print the last element.

print(a[5])

60


In [31]:
# Question:3 Print elements from index 2 to 5.

print(a[2:6])

[30 40 50 60]


In [33]:
#QUuestion:4 Print every alternate element.

print(a[::2])

[10 30 50 70]


In [37]:
#Question:5 Reverse the array

print(a[-1:-8])

[]


In [ ]:
4. Reshaping Arrays

In [40]:
#Create an array containing numbers from 1 to 12.

a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [43]:
# Question:1 Convert it into a 3 × 4 matrix.

np.reshape(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
#Question:2 Convert it into a 2 × 6 matrix.

np.reshape(a,(2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
5. Arithmetic Operations

In [45]:
#Create two arrays:
A = [1, 2, 3, 4, 5]
B = [5, 4, 3, 2, 1]

In [46]:
#Perform:
#Question:1 Addition

np.sum([A,B])

np.int64(30)

In [49]:
#Question:2 Subtraction

np.subtract(A,B)

array([-4, -2,  0,  2,  4])

In [50]:
#Question:3 Multiplication

np.multiply(A,B)

array([5, 8, 9, 8, 5])

In [51]:
#Question:4 Division

np.divide(A,B)

array([0.2, 0.5, 1. , 2. , 5. ])

In [ ]:
6. Statistical Functions

In [53]:
#Create an array:
[12, 25, 18, 40, 30, 15]
a=np.array([12,25,18,40,30,15])
print(a)

[12 25 18 40 30 15]


In [54]:
#Find:
#3Question:1 Sum

np.sum(a)

np.int64(140)

In [55]:
#Question:2 Mean

np.mean(a)

np.float64(23.333333333333332)

In [56]:
#Question:3 Maximum

np.max(a)

np.int64(40)

In [57]:
#Question:4 Minimum

np.min(a)

np.int64(12)

In [58]:
#Question:5 Standard deviation

np.std(a)

np.float64(9.585869229698938)

In [ ]:
7. Random Arrays

In [59]:
#Create:
#A random array of 10 integers between 1 and 100.

a=np.arange(1,100,11)
print(a)


[ 1 12 23 34 45 56 67 78 89]


In [60]:
#Question:1 Find the largest value.

np.max(a)

np.int64(89)

In [61]:
#Question:2 Find the smallest value.

np.min(a)

np.int64(1)

In [62]:
#Question:3 Sort the array

np.sort(a)

array([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [ ]:
8. Boolean Indexing

In [64]:
#Given the array:
a=np.array([5,12,18,25,30,7,40,50])
print(a)

[ 5 12 18 25 30  7 40 50]


In [65]:
#Question:1 Print elements greater than 20.

b=a>20
print(b)

[False False False  True  True False  True  True]


In [66]:
#Question:2 Print even numbers.

print(a[a%2==0])

[12 18 30 40 50]


In [67]:
#Question:3 Count how many numbers are greater than 15

b=a>20
print(b)

[False False False  True  True False  True  True]


In [ ]:
9. Matrix Operations

In [72]:
#Question:1 Find its transpose.

np.transpose(a)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
#Create a 3 × 3 matrix.

a=np.arange(2,11)
print(a)

[ 2  3  4  5  6  7  8  9 10]


In [91]:
x=np.reshape(a,(3,3))
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [86]:
#Question:2 Find the sum of each row

print(x)
print("row 1 sum:",x[0:1].sum())
print("row 2 sum:",x[1:2].sum())
print("row 3 sum:",x[2:3].sum())

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
row 1 sum: 9
row 2 sum: 18
row 3 sum: 27


In [93]:
#Question:3 Find the sum of each column

print(x)
print("column 1 sum:",x[:,0].sum())
print("column 2 sum:",x[:,1].sum())
print("column 3 sum:",x[:,2].sum())

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
column 1 sum: 15
column 2 sum: 18
column 3 sum: 21


In [ ]:
10. Mini Practice Problem

In [73]:
#A student scored the following marks:

a=np.array([65, 72, 88, 45, 90, 55, 78, 84, 60, 95])
print(a)

[65 72 88 45 90 55 78 84 60 95]


In [75]:
#Perform the following:
#Question:1 Find the highest mark.

np.max(a)

np.int64(95)

In [76]:
#Question:2 Find the lowest mark.

np.min(a)

np.int64(45)

In [77]:
#Question:3 Calculate the average mark.

np.mean(a)

np.float64(73.2)

In [78]:
#Question:4 Display marks greater than 75.

b=a>75
print(b)

[False False  True False  True False  True  True False  True]


In [80]:
#Question":5 Count the number of students who scored above 60.

b=len(a[a>60])
print(b)

7


In [79]:
#Question:6 Sort the marks in ascending order

np.sort(a)

array([45, 55, 60, 65, 72, 78, 84, 88, 90, 95])